---
parser: babel-eslint
parserOptions:
  ecmaVersion: 6
  sourceType: "module"
  ecmaFeatures:
    jsx: true
plugins:
  - react
env:
  browser: true
  es6: true
extends:
  - "eslint:recommended"
  - "plugin:react/recommended"
  - "plugin:import/errors"
  - "plugin:import/warnings"
rules:
  no-console: 0
  comma-dangle: [2, "only-multiline"]
  no-inner-declarations: 0
  no-unused-vars: [2, {argsIgnorePattern: "^(nextState|prevState|error)$"}]
  no-use-before-define: [2, {functions: false}]
  no-trailing-spaces: 2
  react/no-did-update-set-state: [1]
  react/no-did-mount-set-state: [1]
  react/no-unused-prop-types: [1]
  react/jsx-no-bind: [1]
  import/no-duplicates: 0

globals:
  module: true
  require: true

settings:
  import/resolver:
    node:
      moduleDirectory:
        - node_modules
        - src/
